keyring_name  = "terraform_test_keyring"
region = "asia-south1"
key_name = "terraform_composer_key"
rotation_period = "2592000s" 
algorithm = "GOOGLE_SYMMETRIC_ENCRYPTION" 
project = "outstanding-pen-389306"